---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
languageSettings:
  - language: "*"
    locale: "en, en-US"
dictionaryDefinitions:
  - name: project-words
    path: "./.cspell.project-words.txt"
    addWords: true
dictionaries: ["project-words"]
ignoreRegExp:
  - '\..*'
ignorePaths:
  - "node_modules"
  - "build"
  - "*.css"
  - "*.svg"
  - "*/**Makefile"
  - "vcs.json"
  - ".env"
noConfigSearch: true
