---
name: vrun-fee

networks:
  proxy:
    name: ${PROXY_DOCKER_NETWORK:-vrun-proxy}
    external: true
  validator:
    name: ${VALIDATOR_DOCKER_NETWORK:-vrun-db_default}
    external: true

configs:
  dot-env:
    file: .env
  signing-key:
    file: signing.key

services:
  api-dev:
    extends: api
    container_name: ${COMPOSE_PROJECT_NAME}-dev
    profiles:
      - dev
    networks:
      - validator
      - proxy

  api:
    container_name: ${COMPOSE_PROJECT_NAME}
    user: ${FEE_USER:-fee}:${FEE_USER:-fee}
    env_file:
      - .env
    build:
      context: ${DOCKER_BUILD_PATH:-.}
      dockerfile: Dockerfile
      args:
        - FEE_USER=${FEE_USER:-fee}
      tags:
        - vrun-fee:local-dev
    profiles:
      - api
    ports:
      - 8082:${FEE_LISTEN_PORT:-8080}
    networks:
      - validator
    configs:
      - source: dot-env
        target: /.env
      - source: signing-key
        target: /usr/share/fee/signing.key
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vrun-fee-api.loadbalancer.server.scheme=http"
      - "traefik.http.routers.vrun-fee-api.rule=PathPrefix(`/fee/`)"
      - "traefik.http.middlewares.vrun-fee-api-strip-prefixes.stripprefix.prefixes=/fee"
      - "traefik.http.middlewares.corsheader-fee.headers.accesscontrolallowmethods=GET,POST,PUT,OPTIONS"
      - "traefik.http.middlewares.corsheader-fee.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.corsheader-fee.headers.accesscontrolalloworiginlist=http://localhost:3000"
      - "traefik.http.middlewares.corsheader-fee.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.corsheader-fee.headers.addvaryheader=true"
      - "traefik.http.routers.vrun-fee-api.middlewares=vrun-fee-api-strip-prefixes,corsheader-fee"
