name: Sanity checks

env:
  TERM: xterm

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codestyle:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make editorconfig-test

  cspell:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make cspell-test

  md-test:
    name: Markdown Broken Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make md-test-links
